### ISSUE TITLE
Bug in shader generator?

### ISSUE THREAD

**Issue by robspearman** [nyyManni/msdfgl#4] opened 2020-03-15 16:40 UTC
I was unable to compile until I manually removed spurious "\n" sequences in the generated _msdfgl_shaders.h

Looks like C lines are being treated like shader lines.

**Comment by nyyManni** [comment] 2020-03-15 16:54
Could you show a few lines from the generated `_msdfgl_shaders.h`? Also, which platform, cmake version and msdfgl revision are you having trouble with?

**Comment by robspearman** [comment] 2020-03-15 17:41
Here are the first four lines:

```
#ifndef _MSDF_SHADERS_H\n#define _MSDF_SHADERS_H
\nconst char * _font_fragment =
"\n"
"precision highp float;\n"
```

CentOS 8 Linux, cmake 3.11.4, using master branch.

Thanks!

**Comment by nyyManni** [comment] 2020-03-15 18:19
Hmmm. I am not able to reproduce that output. That include guard is generated in the shell script `gen-shaders` which is executed during the build. CMake should get rid of the first pair of backslashes, which should result in them becoming newlines in the final shader header.

Does it get resolved with this patch?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ae208c0..09a06ed 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -75,7 +75,8 @@ else ()  # Linux and macOS
 OUTPUT=\$1
 shift

-echo '#ifndef _MSDF_SHADERS_H\\n#define _MSDF_SHADERS_H' >$OUTPUT
+echo '#ifndef _MSDF_SHADERS_H' >$OUTPUT
+echo '#define _MSDF_SHADERS_H' >>$OUTPUT
 for header; do
         fname=\${header##*/};
         echo '\\nconst char * _'\${fname\%\%.glsl}' =' >>\$OUTPUT
```

Maybe you can also add a call to `env` into the aforementioned script, so that it will echo your environment in the build output. Maybe that gives a clue for the root cause.

**Comment by robspearman** [comment] 2020-03-15 19:54
Yes, that fixes the first lines.  This patch fixes the remainder as well.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ae208c0..22d20b9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -75,10 +75,12 @@ else ()  # Linux and macOS
 OUTPUT=\$1
 shift
 
-echo '#ifndef _MSDF_SHADERS_H\\n#define _MSDF_SHADERS_H' >$OUTPUT
+echo '#ifndef _MSDF_SHADERS_H' >$OUTPUT
+echo '#define _MSDF_SHADERS_H' >>$OUTPUT
 for header; do
         fname=\${header##*/};
-        echo '\\nconst char * _'\${fname\%\%.glsl}' =' >>\$OUTPUT
+        echo ''
+        echo 'const char * _'\${fname\%\%.glsl}' =' >>\$OUTPUT
         sed -e 's/\\\\/\\\\\\\\/' \\
             -e 's/^\\(.*\\)\$/\"\\1\\\\n\"/' \\
             \$header >>\$OUTPUT; \\
diff --git a/example/demo.c b/example/demo.c
index 1dbb438..ba03c38 100644
```

I really don't see anything odd in env.  My shell is bash 4.4.19.

**Closed as completed** 2020-03-15 21:04 UTC

**Comment by nyyManni** [comment] 2020-03-15 21:06
I applied the changes from your patch anyway, now on master.
